language: node_js
node_js:
- '6'
script: npm test
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: CJdxoog/jzW122hU0M9GEpTuf6VEN/ro9GCZs9MK3thmW8WLu9yjiWxOGVAnGojuvzymsTT32rgcXguwQo5URmMGzUFFP+KZdRMHjCZ0akw5gxeb3TEieR5bjXZgjQB2avZdIxHbQKaJehiOtaTjXdP91AAo/GbLAYjpqHVlQKQ=
  on:
    tags: true
    repo: noflo/noflo-stripe
